export default {
  files: ['**/*.{js,mjs,ts,tsx}'],
  rules: {
    'arrow-body-style': ['error', 'as-needed'],
    camelcase: 'error',
    complexity: ['error', { max: 4 }],
    'consistent-return': 'error',
    'max-classes-per-file': ['error', 1],
    'max-depth': ['error', 4],
    'max-lines': ['error', 500],
    'max-lines-per-function': ['error', 100],
    'max-nested-callbacks': ['error', 4],
    'max-params': ['error', 5],
    'new-cap': ['error', { newIsCap: true }],
    'no-alert': 'error',
    'no-console': ['error', { allow: ['info', 'warn', 'error'] }],
    'no-else-return': 'error',
    'no-empty-function': 'error',
    'no-empty-static-block': 'error',
    'no-eval': 'error',
    'no-extra-bind': 'error',
    'no-extra-boolean-cast': 'error',
    'no-implicit-coercion': 'error',
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'no-invalid-this': 'error',
    'no-lone-blocks': 'error',
    'no-lonely-if': 'error',
    'no-loop-func': 'error',
    'no-multi-assign': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-sequences': 'error',
    'no-unneeded-ternary': 'error',
    'no-unused-expressions': 'error',
    'no-useless-call': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-void': 'error',
    'prefer-const': 'error',
    // "sort-imports": "error",
    // "sort-keys": "error",
    // "sort-vars": "error",
  },
};
